name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev", "staging" ]

permissions:
  issues: write
  pull-requests: write  # ✅ Allows commenting on PRs

jobs:
  lint-prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci

    - name: Lint Check
      run: npm run lint
    
    - name: Checking format
      run: npm run format:check

  build:
    runs-on: ubuntu-latest
    needs: lint-prettier

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies 
      run: npm ci

    - name: Run Build
      run: npm run build

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Notify GitHub on Failure
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request?.number || 0,
            body: "🚨 GitHub Actions workflow failed! Check logs: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          });

  comment-on-pr:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Comment on PR
      if: github.event_name == 'pull_request' && success()
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
        -d '{"body": "✅ GitHub Actions workflow succeeded! 🎉 Check it here: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}'
