name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev", "stagging"]

jobs:
  lint-prettier:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci

    - name: Lint Check
      run: npm run lint
    
    - name: Checking format
      run: npm run format:check
 
  build:

    runs-on: ubuntu-latest
    needs: lint-prettier

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
   
    - name: Install Dependencies 
      run: npm ci
    - name: Run Build
      run: npm run build